# permissions for end users to edit hotelreservationapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hotelreservationapp-editor-role
rules:
- apiGroups:
  - example.njtech.edu.cn
  resources:
  - hotelreservationapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.njtech.edu.cn
  resources:
  - hotelreservationapps/status
  verbs:
  - get
