# permissions for end users to view hotelreservationapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hotelreservationapp-viewer-role
rules:
- apiGroups:
  - example.njtech.edu.cn
  resources:
  - hotelreservationapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.njtech.edu.cn
  resources:
  - hotelreservationapps/status
  verbs:
  - get
